name: runGcloud
on:
  workflow_dispatch:
jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          # create_credentials_file: true
          workload_identity_provider: 'projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.POOL_ID }}/providers/${{ vars.PROVIDER_ID }}'
          service_account: '${{ vars.SERVICE_ACCOUNT_EMAIL }}'
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Describe my-service-account
        run: gcloud iam service-accounts describe '${{ vars.SERVICE_ACCOUNT_EMAIL }}'