name: runGcloud
on:
  workflow_dispatch:
jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          # create_credentials_file: true
          workload_identity_provider: 'projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.POOL_ID }}/providers/${{ vars.PROVIDER_ID }}'
          service_account: '${{ vars.SERVICE_ACCOUNT_EMAIL }}'
      
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'hello-cloud-run'
          image: 'gcr.io/cloudrun/hello'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'